# -*- coding: utf-8 -*-
"""tarte月次売上集計.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/lovecheepao/af0999702e960cd84ce51f03708e3407/tarte.ipynb

### 🧭 使用手順

1. まず、対象の期間で絞り込んだ下記①〜④のファイルを用意し、
「tarte事業管理課2023／売上等データ」フォルダの直下に格納してください。
2. 上から順にセルの左側の「▶️」マークをクリックして、コードを実行してください。(一つのセルが終了してから次のを押してください）
3. 各ステップで指定のファイルをアップロードします。
4. 最後まで実行すると、データ（顧客データベース、注文別集計、商品実績）が自動でGoogleスプレッドシート「tarte 実績データベース」に追加されます。

---

### 📁 必要なファイル一覧

| ファイル名              | データ内容         | 格納 or 出力場所          |
| ------------------ | ----------- | ----------- |
| ①sales.csv          | ECの注文明細 | BOの注文検索で出力　※キャンセル/返品 未記入で抽出       |
| ②sales\_history.csv | ECの注文明細（年齢付き） | BOの購入ヒストリーで出力   |
| ③customer.csv       | ECの会員番号と会員登録日 |BOの会員情報で出力   |
| キャンペーン割引マスタ.xlsx | ECのキャンペーン割引率一覧 |「tarte事業管理課2023/売上等データ」直下にあります |
| ④ZC870 明細出力.xlsx       | 店舗の注文明細 | KOMPASの明細出力で出力   |
| category.csv       | カテゴリーなど商品情報 | 「tarte事業管理課2023/売上等データ」直下にあります   |

---

### ⚠️ 注意事項

* ファイル名や形式が異なる場合は、エラーになることがあります。
* アップロードは、**求められたタイミングで**行ってください。

# **ステップ1:** **必要なライブラリのインストール＆Googleドライブにマウント**
"""

# ✅ 必要なライブラリのインストール
!pip install --upgrade gspread gspread_dataframe japanize_matplotlib --quiet

# ✅ 認証＆ドライブマウント
from google.colab import drive
drive.mount('/content/drive')

# ✅ Googleアカウント認証 ←これを追加！
from google.colab import auth
auth.authenticate_user()

# ✅ 認証とAPI操作
import gspread
from google.auth import default
from gspread_dataframe import set_with_dataframe, get_as_dataframe
creds, _ = default()
gc = gspread.authorize(creds)

# ✅ ディレクトリ移動（ドライブ内の任意フォルダへ）
import os
os.chdir('/content/drive/MyDrive/')

# ✅ 分析用ライブラリ
import pandas as pd
import matplotlib.pyplot as plt
import japanize_matplotlib
import seaborn as sns
from datetime import date

# ✅ 日本語フォント設定（Seaborn）
sns.set(font=['IPAexGothic'])

# ✅ ファイルアップロードなどで使うモジュール
from google.colab import files

"""# **ステップ2:** **ECの注文明細を注文、商品ごとに集計する**

✅①sales.csv ②sales_history.csv ③category.csv ④キャンペーン割引マスタ.xlsxを複数選択してまとめてアップロードしてください
"""

# ファイルのアップロード
uploaded = files.upload()
uploaded_files = list(uploaded.keys())

# ファイル名を自動特定
sales_file = next((f for f in uploaded_files if f.startswith('sales') and 'history' not in f), None)
members_file = next((f for f in uploaded_files if f.startswith('sales_history')), None)
category_file = next((f for f in uploaded_files if f.startswith('category')), None)
campaign_file = next((f for f in uploaded_files if f.startswith('キャンペーン')), None)

assert sales_file and members_file and category_file and campaign_file, "必要なファイルが見つかりません"

# 売上データの読み込み・加工
sd = pd.read_csv(sales_file, encoding='cp932')
sd['注文日'] = pd.to_datetime(sd['注文日'])
sd = sd[(sd['税抜単価'] > 0) & (sd['数量'] > 0)]
sd['商品符号'] = sd['商品コード'].astype(str).str[:4].str.strip()
sd['税抜合計金額'] = sd['数量'] * sd['税抜単価']

# チュービングマスカラ分析
def analyze_tubing_crosssell_detail(sd, product_code_travel='TRHM001', product_code_full='TRHL001'):
    tubing_codes = [product_code_travel, product_code_full]
    tubing_df = sd[sd['商品コード'].isin(tubing_codes)].copy()
    first_purchase_dates = tubing_df.groupby('会員番号')['注文日'].min().reset_index()
    return first_purchase_dates, tubing_codes

first_purchase_dates, tubing_codes = analyze_tubing_crosssell_detail(sd)

# 会員情報をマージ
members = pd.read_csv(members_file, encoding='cp932', skiprows=5, on_bad_lines='skip')
members = members[['会員番号', '年齢']].drop_duplicates()
sd = pd.merge(sd, members, on='会員番号', how='left')
sd['年齢'] = pd.to_numeric(sd['年齢'], errors='coerce').astype('Int64')

#年代変換
def convert_to_age_group(age):
    if pd.isnull(age) or age < 10 or age > 130:
        return '不明'
    if age < 70:
        return f"{(age // 10) * 10}代"
    return '70代以上'

sd['年代'] = sd['年齢'].apply(convert_to_age_group)

# 割引計算
df_discount = pd.read_excel(campaign_file)
df_discount['キャンペーン開始日'] = pd.to_datetime(df_discount['キャンペーン開始日'])
df_discount['キャンペーン終了日'] = pd.to_datetime(df_discount['キャンペーン終了日'])

percentage_discounts = df_discount[df_discount['割引率'] < 1]
fixed_discounts = df_discount[df_discount['割引率'] >= 1]

sd['割引率'] = 0.0
sd['税抜割引後単価'] = sd['税抜単価']
sd['税抜割引後金額'] = sd['税抜合計金額']

# 割合割引の適用（商品コードベース）
for _, row in percentage_discounts.iterrows():
    mask = (
        sd['適用キャンペーン'].astype(str).str.contains(str(row['キャンペーンID']), na=False) &
        (sd['商品コード'].astype(str) == str(row['商品コード'])) &  # 商品コード同士で比較
        (sd['注文日'] >= row['キャンペーン開始日']) &
        (sd['注文日'] <= row['キャンペーン終了日'])
    )
    sd.loc[mask, '割引率'] = row['割引率']

    # 割引後金額を計算
    sd.loc[mask, '税抜割引後単価'] = sd.loc[mask, '税抜単価'] * (1 - row['割引率'])
    sd.loc[mask, '税抜割引後金額'] = sd.loc[mask, '数量'] * sd.loc[mask, '税抜割引後単価']

    # 特別キャンペーン追加割引
    target_rows = sd[mask]
    for order_no in target_rows['注文番号'].unique():
        special_campaign = sd[
            (sd['注文番号'] == order_no) &
            (sd['適用キャンペーン'].astype(str).str.contains('tarte-live230308cp', na=False))
        ]
        if not special_campaign.empty:
            additional_mask = (
                (sd['注文番号'] == order_no) &
                (sd['商品コード'].astype(str) == str(row['商品コード']))
            )
            # 追加割引を適用
            sd.loc[additional_mask, '割引率'] += 0.10
            current_discount_rate = sd.loc[additional_mask, '割引率'].iloc[0]
            sd.loc[additional_mask, '税抜割引後単価'] = sd.loc[additional_mask, '税抜単価'] * (1 - current_discount_rate)
            sd.loc[additional_mask, '税抜割引後金額'] = sd.loc[additional_mask, '数量'] * sd.loc[additional_mask, '税抜割引後単価']

# tarte230824cp-a と tarte230824cp-b 以外の定額割引だけ処理
fixed_discounts_exclude_ab = fixed_discounts[
    ~fixed_discounts['キャンペーンID'].isin(['tarte230824cp-a', 'tarte230824cp-b'])
]

for _, row in fixed_discounts_exclude_ab.iterrows():
    target_rows = sd[
        sd['適用キャンペーン'].astype(str).str.contains(str(row['キャンペーンID']), na=False) &
        (sd['商品コード'].astype(str) == str(row['商品コード'])) &
        (sd['注文日'] >= row['キャンペーン開始日']) &
        (sd['注文日'] <= row['キャンペーン終了日'])
    ]
    for order_no in target_rows['注文番号'].unique():
        order_mask = sd['注文番号'] == order_no
        total = sd.loc[order_mask, '税抜割引後金額'].sum()
        if total > 0:
            ratio = sd.loc[order_mask, '税抜割引後金額'] / total
            fixed_discount_amount = row['割引率']
            sd.loc[order_mask, '税抜割引後金額'] -= ratio * fixed_discount_amount

# tarte230824cp-a だけを注文単位で重複適用しないように処理
target_campaign_id = 'tarte230824cp-a'
applied_orders = set()

for _, row in fixed_discounts[fixed_discounts['キャンペーンID'] == target_campaign_id].iterrows():
    target_rows = sd[
        sd['適用キャンペーン'].astype(str).str.contains(str(row['キャンペーンID']), na=False) &
        (sd['商品コード'].astype(str) == str(row['商品コード'])) &
        (sd['注文日'] >= row['キャンペーン開始日']) &
        (sd['注文日'] <= row['キャンペーン終了日'])
    ]

    for order_no in target_rows['注文番号'].unique():
        if order_no in applied_orders:
            continue  # すでに割引適用済みなのでスキップ！
        order_mask = sd['注文番号'] == order_no
        total = sd.loc[order_mask, '税抜割引後金額'].sum()
        if total > 0:
            ratio = sd.loc[order_mask, '税抜割引後金額'] / total
            sd.loc[order_mask, '税抜割引後金額'] -= ratio * row['割引率']
        applied_orders.add(order_no)

# tarte230824cp-b だけを注文単位で重複適用しないように処理
target_campaign_id_b = 'tarte230824cp-b'
applied_orders_b = set()

for _, row in fixed_discounts[fixed_discounts['キャンペーンID'] == target_campaign_id_b].iterrows():
    target_rows = sd[
        sd['適用キャンペーン'].astype(str).str.contains(str(row['キャンペーンID']), na=False) &
        (sd['商品コード'].astype(str) == str(row['商品コード'])) &
        (sd['注文日'] >= row['キャンペーン開始日']) &
        (sd['注文日'] <= row['キャンペーン終了日'])
    ]

    for order_no in target_rows['注文番号'].unique():
        if order_no in applied_orders_b:
            continue  # すでに割引適用済みなのでスキップ！
        order_mask = sd['注文番号'] == order_no
        total = sd.loc[order_mask, '税抜割引後金額'].sum()
        if total > 0:
            ratio = sd.loc[order_mask, '税抜割引後金額'] / total
            sd.loc[order_mask, '税抜割引後金額'] -= ratio * row['割引率']
        applied_orders_b.add(order_no)

# デバッグ用：割引適用状況の確認
print("割引適用状況:")
discount_applied = sd[sd['割引率'] > 0]
if len(discount_applied) > 0:
    print(f"割引適用件数: {len(discount_applied):,}件")
    print(discount_applied[['注文番号', '商品コード', '商品符号', '割引率', '税抜単価', '税抜割引後単価']].head())
else:
    print("割引が適用された商品はありません。")

# データ集計
order_meta = sd[['注文番号', '注文日', '会員番号', '年代', '注文者都道府県', '適用キャンペーン']].drop_duplicates(subset='注文番号').copy()
order_meta['年月'] = order_meta['注文日'].dt.to_period('M').astype(str)

# ✅ ライブ購入フラグを付与 ライブ購入フラグが1のキャンペーンIDを抽出
live_campaigns = df_discount[df_discount['ライブ購入フラグ'] == 1]['キャンペーンID'].dropna().unique().tolist()

order_meta['ライブ購入フラグ'] = 0

for campaign_id in live_campaigns:
    mask = order_meta['適用キャンペーン'].astype(str).str.contains(str(campaign_id), na=False)
    order_meta.loc[mask, 'ライブ購入フラグ'] = 1

order_detail_summary = sd.groupby(['注文番号', '商品コード'], as_index=False).agg({
    '数量': 'sum',
    '税抜合計金額': 'sum',
    '税抜割引後金額': 'sum'
})

order_detail_summary = pd.merge(order_detail_summary, order_meta, on='注文番号', how='left')

# 月次実績でも商品コードが必要なので追加
monthly_category = order_detail_summary.groupby(['年月', '商品コード'], as_index=False).agg({
    '数量': 'sum',
    '税抜割引後金額': 'sum'
})

# 商品マスタ結合（商品コードベースで統一）
category_master = pd.read_csv(category_file, encoding='cp932')
category_master.columns = category_master.columns.str.strip()
category_master['商品符号'] = category_master['商品符号'].astype(str).str.strip()
category_master['商品コード'] = category_master['商品コード'].astype(str).str.strip()

# 商品コードベースの商品マスタを作成
product_info_cols = ['商品コード', '商品名', 'メインカテゴリー', 'サブカテゴリー', 'サブサブカテゴリー']
product_master_by_code = category_master[product_info_cols].drop_duplicates(subset='商品コード', keep='first')

# 商品符号情報を商品マスタから取得
symbol_master = category_master[['商品コード', '商品符号']].drop_duplicates(subset='商品コード', keep='first')

# order_detail_summaryに商品符号を追加
order_detail_summary = pd.merge(order_detail_summary, symbol_master, on='商品コード', how='left')

# 商品情報を結合
order_detail_summary = pd.merge(order_detail_summary, product_master_by_code, on='商品コード', how='left')

# チュービング初回購入フラグ付与
order_detail_summary = pd.merge(
    order_detail_summary,
    first_purchase_dates.rename(columns={'注文日': 'チュービング初回購入日'}),
    on='会員番号',
    how='left'
)
order_detail_summary['チュービング初回購入フラグ'] = (
    (order_detail_summary['商品符号'].isin(['TRHM', 'TRHL'])) &
    (order_detail_summary['注文日'] == order_detail_summary['チュービング初回購入日'])
).astype(int)
order_detail_summary.drop(columns=['チュービング初回購入日'], inplace=True)

# チュービング購入情報
tubing_orders = (
    sd[sd['商品コード'].isin(tubing_codes)]
    .groupby('注文番号', as_index=False)['数量']
    .sum()
    .rename(columns={'数量': '注文内チュービング購入本数'})
)
tubing_orders['注文内チュービング購入回数'] = 1

order_detail_summary = pd.merge(
    order_detail_summary,
    tubing_orders[['注文番号', '注文内チュービング購入回数', '注文内チュービング購入本数']],
    on=['注文番号'],
    how='left'
)

order_detail_summary['注文内チュービング購入本数'] = order_detail_summary.apply(
    lambda row: row['注文内チュービング購入本数'] if row['商品符号'] in ['TRHM', 'TRHL'] else 0,
    axis=1
)
order_detail_summary['注文内チュービング購入回数'] = order_detail_summary.apply(
    lambda row: row['注文内チュービング購入回数'] if row['商品符号'] in ['TRHM', 'TRHL'] else 0,
    axis=1
)

# 月次実績にも商品コードで商品情報を結合
monthly_category = pd.merge(monthly_category, symbol_master, on='商品コード', how='left')
monthly_category = pd.merge(monthly_category, product_master_by_code, on='商品コード', how='left')

# カラム順序調整
order_detail_cols = [
    '注文番号', '商品符号', '商品コード', '商品名', 'メインカテゴリー', 'サブカテゴリー', 'サブサブカテゴリー',
    '数量','税抜合計金額', '税抜割引後金額', '注文日', '会員番号', '年代', '注文者都道府県',
    '適用キャンペーン','ライブ購入フラグ', '年月','チュービング初回購入フラグ','注文内チュービング購入本数'
]
order_detail_summary = order_detail_summary[order_detail_cols]
order_detail_summary = order_detail_summary.sort_values('注文日', ascending=False)

monthly_category_cols = [
    '年月', '商品符号', '商品コード', '商品名', 'メインカテゴリー', 'サブカテゴリー', 'サブサブカテゴリー',
    '数量', '税抜割引後金額'
]
monthly_category = monthly_category[monthly_category_cols]
monthly_category["年月"] = monthly_category["年月"].astype(str)

# スプレッドシートを開く
spreadsheet = gc.open("tarte 実績データベース")
worksheet_order = spreadsheet.worksheet("注文商品明細（EC）")
worksheet_category = spreadsheet.worksheet("商品実績（EC）")

# 注文商品明細（EC）に追記
existing_order = get_as_dataframe(worksheet_order, evaluate_formulas=True).dropna(how='all')
combined_order = pd.concat([existing_order, order_detail_summary], ignore_index=True).drop_duplicates(subset=['注文番号', '商品コード'])

# 全体を注文日で降順に並べる
combined_order['注文日'] = pd.to_datetime(combined_order['注文日'], errors='coerce')
combined_order = combined_order.sort_values('注文日', ascending=False)

worksheet_order.clear()
set_with_dataframe(worksheet_order, combined_order)

# 商品実績（EC）を加算更新で追記　既存データを取得
existing_category = get_as_dataframe(worksheet_category, evaluate_formulas=True).dropna(how='all')

# もし既存データが空なら、空のDataFrameを用意
if existing_category.empty:
    existing_category = pd.DataFrame(columns=['年月', '商品コード', '商品符号',
                                              '商品名', 'メインカテゴリー', 'サブカテゴリー',
                                              'サブサブカテゴリー', '数量', '税抜割引後金額'])

# 既存データも同じ
if not existing_category.empty:
    existing_category["年月"] = pd.to_datetime(existing_category["年月"], errors='coerce')

# 月次商品別集計データと既存データを合算
combined_category = pd.concat([existing_category, monthly_category], ignore_index=True)

# 必要な列を型整備
combined_category['年月'] = pd.to_datetime(combined_category['年月'], errors='coerce')
combined_category['商品コード'] = combined_category['商品コード'].astype(str)
combined_category['商品符号'] = combined_category['商品符号'].astype(str)

for col in ['数量', '税抜割引後金額']:
    combined_category[col] = pd.to_numeric(combined_category[col], errors='coerce').fillna(0)

# 商品コード単位で合算
aggregated = combined_category.groupby(['年月', '商品コード'], as_index=False).agg({
    '商品符号': 'first',
    '商品名': 'first',
    'メインカテゴリー': 'first',
    'サブカテゴリー': 'first',
    'サブサブカテゴリー': 'first',
    '数量': 'sum',
    '税抜割引後金額': 'sum'
})

aggregated = aggregated.sort_values('年月', ascending=False)

# 保存
worksheet_category.clear()
set_with_dataframe(worksheet_category, aggregated)

print(f"✅ 処理完了：")
print(f"・商品実績（EC）：{len(monthly_category):,}件を対象に、既存の同月・同商品データを上書きしました")
print(f"・注文明細（EC）：{len(order_detail_summary):,}件を既存明細に追記しました（注文番号＋商品符号で重複排除済）")

"""# **ステップ3: ECのtarte顧客データベースに今月分の注文を追記**

✅①customer.csv をアップロードしてください
"""

# スプレッドシート名とシート名
spreadsheet_name = "tarte 実績データベース"
worksheet_name = "顧客データベース（EC）"
spreadsheet = gc.open(spreadsheet_name)
worksheet = spreadsheet.worksheet(worksheet_name)

# 既存の顧客データベース（EC）を取得
df_master = get_as_dataframe(worksheet, evaluate_formulas=True).dropna(how='all')

# ------------------------------------------
# 1. 会員情報ファイル（CSV）のアップロードと読み込み
# ------------------------------------------
print("🔄 会員情報ファイルをアップロードしてください")
uploaded = files.upload()
uploaded_files = list(uploaded.keys())
members_file = next((f for f in uploaded_files if 'customer' in f.lower() and f.endswith('.csv')), None)
assert members_file, "会員情報ファイル（customer*.csv）が見つかりません"

df_members = pd.read_csv(members_file, encoding='cp932').rename(columns=str.strip)
df_members['登録日'] = pd.to_datetime(df_members['登録日'], errors='coerce')

# ------------------------------------------
# 2. 注文明細データ（order_detail_summary）を前提として使用
# ------------------------------------------
df_orders = order_detail_summary.copy()
df_orders['注文日'] = pd.to_datetime(df_orders['注文日'], errors='coerce')

# ------------------------------------------
# 3. 整合性チェック
# ------------------------------------------
for df, cols, name in [(df_master, ['会員番号', '注文番号'], '顧客マスタ'),
                       (df_members, ['会員番号'], '会員情報'),
                       (df_orders, ['会員番号', '注文番号', '商品符号'], '注文明細')]:
    for col in cols:
        if col not in df.columns:
            raise ValueError(f"❌ {name} にカラムが不足しています: {col}")

# ------------------------------------------
# 4. 会員情報をマージしてカラムを整理
# ------------------------------------------
for df in [df_members, df_orders, df_master]:
    df['会員番号'] = pd.to_numeric(df['会員番号'], errors='coerce').astype(pd.Int64Dtype()).astype(str)

if df_members['会員番号'].duplicated().sum() > 0:
    df_members = df_members.sort_values('登録日', ascending=False).drop_duplicates('会員番号')

df_orders = pd.merge(df_orders, df_members[['会員番号', '登録日']], on='会員番号', how='left')

COLUMN_ORDER = ['会員番号', '年代', '都道府県', '会員登録日', '注文日', '注文番号',
                '商品符号','商品コード', '商品名', 'メインカテゴリー', 'サブカテゴリー', 'サブサブカテゴリー',
                '数量', '税抜割引後金額', 'ライブ購入フラグ', 'ブランド新規', 'メゾン新規']
df_orders_renamed = df_orders.rename(columns={'登録日': '会員登録日', '注文者都道府県': '都道府県'})
df_orders_renamed['ブランド新規'] = df_orders_renamed['メゾン新規'] = 0

for col in COLUMN_ORDER:
    if col not in df_orders_renamed.columns:
        df_orders_renamed[col] = None
    if col not in df_master.columns:
        df_master[col] = None

df_orders_renamed = df_orders_renamed[COLUMN_ORDER]
df_master = df_master[COLUMN_ORDER]

# 5. 注文キー作成と新規抽出・フラグ付与 (完全修正版)

df_master['注文キー'] = (
    df_master['注文番号'].astype(str) + '_' +
    df_master['商品符号'].astype(str) + '_' +
    df_master['商品コード'].astype(str)
)
df_orders_renamed['注文キー'] = (
    df_orders_renamed['注文番号'].astype(str) + '_' +
    df_orders_renamed['商品符号'].astype(str) + '_' +
    df_orders_renamed['商品コード'].astype(str)
)

新規キー = set(df_orders_renamed['注文キー']) - set(df_master['注文キー'])
df_new_orders_only = df_orders_renamed[df_orders_renamed['注文キー'].isin(新規キー)].copy()

if len(df_new_orders_only) > 0:
    # 既存の会員別最古注文日
    existing_first_orders = (
        df_master.groupby('会員番号')['注文日'].min()
        .reset_index().rename(columns={'注文日': '既存最古注文日'})
    )

    # 今回追加分に結合
    df_new_orders_only = pd.merge(
        df_new_orders_only,
        existing_first_orders,
        on='会員番号',
        how='left'
    )

    # 今回最古注文日
    df_new_orders_only['今回最古注文日'] = df_new_orders_only.groupby('会員番号')['注文日'].transform('min')

    # ブランド新規：既存最古がNaT かつ 今回最古
    df_new_orders_only['ブランド新規'] = (
        df_new_orders_only['既存最古注文日'].isna() &
        (df_new_orders_only['注文日'] == df_new_orders_only['今回最古注文日'])
    ).astype(int)

    # メゾン新規
    df_new_orders_only['メゾン新規'] = (
        (df_new_orders_only['注文日'] - df_new_orders_only['会員登録日']).dt.days <= 7
    ).fillna(False).astype(int)

    # 不要列削除
    df_new_orders_only = df_new_orders_only.drop(columns=['既存最古注文日', '今回最古注文日'])

    # 新しいマスタ
    df_new_master = pd.concat([df_master, df_new_orders_only], ignore_index=True).drop_duplicates('注文キー', keep='last')
else:
    df_new_master = df_master.copy()

df_new_master = df_new_master.sort_values(by=['注文日', '注文番号', '商品符号']).drop(columns='注文キー', errors='ignore')

# ------------------------------------------
# 6. Googleスプレッドシートに追記・保存
# ------------------------------------------
# スプレッドシートからの既存データ取得後
existing_data = get_as_dataframe(worksheet, evaluate_formulas=True).dropna(how='all')

# 日付列を datetime 型に変換しておく（←これが重要！）
for col in ['注文日', '会員登録日']:
    if col in existing_data.columns:
        existing_data[col] = pd.to_datetime(existing_data[col], errors='coerce')

# 以下、いつも通り結合・重複排除
combined_data = pd.concat([existing_data, df_new_master], ignore_index=True)

# 注文キーを「注文番号 + 商品符号 + 商品コード」で作成
combined_data['注文キー'] = (
    combined_data['注文番号'].astype(str) + '_' +
    combined_data['商品符号'].astype(str) + '_' +
    combined_data['商品コード'].astype(str)
)

# 念のため、ここでも再度型統一（安全性高め）
combined_data['注文日'] = pd.to_datetime(combined_data['注文日'], errors='coerce')

# 注文キーで重複除去（最新のものを残す）
combined_data = combined_data.sort_values('注文日', ascending=False).drop_duplicates('注文キー', keep='first')

# 不要な列を削除
combined_data = combined_data.drop(columns='注文キー')
combined_data = combined_data.drop(columns=['初回注文日'], errors='ignore')

#注文日降順で並べ替え
combined_data = combined_data.sort_values('注文日', ascending=False)

# スプレッドシートに保存
worksheet.clear()
set_with_dataframe(worksheet, combined_data)

print(f"✅ スプレッドシートに追記完了！現在の件数: {len(combined_data):,}")

"""# **ステップ4:** **店舗の注文明細を注文、商品ごとに集計する**

✅①ZC870 明細出力.xlsxをアップロードしてください
"""

# 1. ファイルのアップロード
uploaded = files.upload()
uploaded_files = list(uploaded.keys())

storesales_file = next((f for f in uploaded_files if f.startswith('ZC870')), None)
assert storesales_file is not None, "売上データが見つかりません。"

# 2. 売上データ読み込み・前処理
print("🔄 売上データ読み込み中...")
ssd = pd.read_excel(storesales_file)
ssd['年月日'] = pd.to_datetime(ssd['年月日'], errors='coerce')
ssd['商品コード'] = ssd['商品符号(7桁)'].astype(str)
ssd['商品符号'] = ssd['商品符号(7桁)'].astype(str).str[:4]
ssd['生年月日'] = pd.to_datetime(ssd['生年月日'], errors='coerce').dt.date
ssd = ssd.rename(columns={
    '税抜割引後金額': '割引後合計金額'
})

# 年齢と年代
today = date.today()
ssd['年齢'] = ssd['生年月日'].apply(lambda x: today.year - x.year - ((today.month, today.day) < (x.month, x.day)) if pd.notnull(x) else None)
ssd['年代'] = ssd['年齢'].apply(convert_to_age_group)

# 注文メタ情報
order_meta = ssd[['店消実績ID', '年月日', '顧客コード', '年代', '店舗名', '客区分名称']].drop_duplicates('店消実績ID')
order_meta['年月'] = order_meta['年月日'].dt.to_period('M').astype(str)

# 注文明細の集計（商品コード単位、商品符号列は保持）
order_detail = ssd.groupby(['店消実績ID', '商品符号', '商品コード'], as_index=False).agg({'数量': 'sum', '割引後合計金額': 'sum'})
order_detail = pd.merge(order_detail, order_meta, on='店消実績ID', how='left')

# 月次集計（年月＋商品コード単位、商品符号も出力に残す）
monthly_summary = order_detail.groupby(['年月', '商品符号', '商品コード'], as_index=False).agg({'数量': 'sum', '割引後合計金額': 'sum'})

# 注文明細・月次実績にマスタ情報を結合
order_detail = pd.merge(order_detail, product_master_by_code, on='商品コード', how='left')
monthly_summary = pd.merge(monthly_summary, product_master_by_code, on='商品コード', how='left')

# 並び順を指定
desired_columns = [
    '店消実績ID',
    '商品符号',
    '商品コード',
    '商品名',
    'メインカテゴリー',
    'サブカテゴリー',
    'サブサブカテゴリー',
    '数量',
    '割引後合計金額',
    '年月日',
    '顧客コード',
    '年代',
    '店舗名',
    '客区分名称',
    '年月'
]

# 必要な列だけ抜き出して順序を並べる
order_detail = order_detail.loc[:, desired_columns]

# 並び替え
order_detail = order_detail.sort_values('年月日', ascending=False)

# 最終出力
print("\n✅ データ集計完了")
print(f"  注文明細件数: {len(order_detail):,}")
print(f"  月次集計件数: {len(monthly_summary):,}")

# スプレッドシートとシート名を指定
spreadsheet_name = "tarte 実績データベース"
spreadsheet = gc.open(spreadsheet_name)

# 注文商品明細（店舗）の追記
worksheet_storeorder = spreadsheet.worksheet("注文商品明細（店舗）")
existing_order_store = get_as_dataframe(worksheet_storeorder, evaluate_formulas=True).dropna(how='all')
combined_order_store = pd.concat([existing_order_store, order_detail], ignore_index=True).drop_duplicates(subset=['店消実績ID', '商品コード'])

combined_order_store['年月日'] = pd.to_datetime(combined_order_store['年月日'], errors='coerce')
combined_order_store = combined_order_store.sort_values('年月日', ascending=False)

worksheet_storeorder.clear()
set_with_dataframe(worksheet_storeorder, combined_order_store)

# 商品実績（店舗）の加算更新
worksheet_storecategory = spreadsheet.worksheet("商品実績（店舗）")
existing_category_store = get_as_dataframe(worksheet_storecategory, evaluate_formulas=True).dropna(how='all')

# 空なら列構造だけ準備
if existing_category_store.empty:
    existing_category_store = pd.DataFrame(columns=[
        '年月', '商品コード', '商品符号',
        '商品名', 'メインカテゴリー', 'サブカテゴリー', 'サブサブカテゴリー',
        '数量', '割引後合計金額'
    ])

# 年月を文字列に統一
monthly_summary['年月'] = monthly_summary['年月'].astype(str)
existing_category_store['年月'] = existing_category_store['年月'].astype(str)

# 型揃え
monthly_summary['商品コード'] = monthly_summary['商品コード'].astype(str)
existing_category_store['商品コード'] = existing_category_store['商品コード'].astype(str)
monthly_summary['商品符号'] = monthly_summary['商品符号'].astype(str)
existing_category_store['商品符号'] = existing_category_store['商品符号'].astype(str)

# 数値化
for col in ['数量', '割引後合計金額']:
    monthly_summary[col] = pd.to_numeric(monthly_summary[col], errors='coerce').fillna(0)
    existing_category_store[col] = pd.to_numeric(existing_category_store[col], errors='coerce').fillna(0)

# 新旧データを結合
combined_store_category = pd.concat([existing_category_store, monthly_summary], ignore_index=True)

# 「年月 × 商品コード」で集計
aggregated_store = combined_store_category.groupby(['年月', '商品コード'], as_index=False).agg({
    '商品符号': 'first',
    '商品名': 'first',
    'メインカテゴリー': 'first',
    'サブカテゴリー': 'first',
    'サブサブカテゴリー': 'first',
    '数量': 'sum',
    '割引後合計金額': 'sum'
}).sort_values('年月', ascending=False)

# スプレッドシートへ保存
worksheet_storecategory.clear()
set_with_dataframe(worksheet_storecategory, aggregated_store)

print("\n✅ ファイル保存完了")

"""# **ステップ5:** **店舗のtarte顧客データベースに今月分の注文を追記**"""

# スプレッドシートの準備
spreadsheet_name = "tarte 実績データベース"
worksheet_name = "顧客データベース（店舗）"
spreadsheet = gc.open(spreadsheet_name)
worksheet_storecustomer = spreadsheet.worksheet(worksheet_name)

# 既存データ取得
df_master = get_as_dataframe(worksheet_storecustomer, evaluate_formulas=True).dropna(how='all')
df_master.columns = df_master.columns.str.strip()
df_master['年月日'] = pd.to_datetime(df_master['年月日'], errors='coerce')

# ------------------------------------------
# 1. 注文別データ（order_detailを使用）
# ------------------------------------------
df_orders = order_detail.copy()
df_orders_renamed = df_orders.copy()

# 年月日・店舗名の補完（列が存在する場合のみ）
if '年月日' in df_orders.columns and df_orders_renamed['年月日'].isna().all():
    df_orders_renamed['年月日'] = df_orders['年月日']
if '店舗名' in df_orders.columns and df_orders_renamed['店舗名'].isna().all():
    df_orders_renamed['店舗名'] = df_orders['店舗名']

# ------------------------------------------
# 2. カラム統一と不足列補完
# ------------------------------------------
COLUMN_ORDER = [
    '顧客コード', '年代', '年月日', '客区分名称', '店消実績ID','商品符号',
    '商品コード','商品名','メインカテゴリー','サブカテゴリー','サブサブカテゴリー','数量', '割引後合計金額', '店舗名', 'ブランド新規', 'メゾン新規'
]
df_orders_renamed['ブランド新規'] = 0
df_orders_renamed['メゾン新規'] = 0

for col in COLUMN_ORDER:
    if col not in df_orders_renamed.columns:
        df_orders_renamed[col] = pd.NA
    if col not in df_master.columns:
        df_master[col] = pd.NA

df_orders_renamed = df_orders_renamed.loc[:, COLUMN_ORDER]
df_master = df_master.loc[:, COLUMN_ORDER]

# 顧客コードの型を揃える
for df in [df_master, df_orders_renamed]:
    df['顧客コード'] = (
        pd.to_numeric(df['顧客コード'], errors='coerce')
        .astype('Int64')
        .astype(str)
    )

# ------------------------------------------
# 3. 新規注文の抽出
# ------------------------------------------
# 注文キーを作成
df_master['注文キー'] = (
    df_master['店消実績ID'].astype(str) + '_' +
    df_master['商品符号'].astype(str) + '_' +
    df_master['商品コード'].astype(str)
)
df_orders_renamed['注文キー'] = (
    df_orders_renamed['店消実績ID'].astype(str) + '_' +
    df_orders_renamed['商品符号'].astype(str) + '_' +
    df_orders_renamed['商品コード'].astype(str)
)

# 新規キー判定
既存注文キー = set(df_master['注文キー'])
df_new_orders_only = df_orders_renamed[~df_orders_renamed['注文キー'].isin(既存注文キー)].copy()

# ------------------------------------------
# 4. フラグ付与（ブランド新規・メゾン新規）
# ------------------------------------------
df_all = pd.concat([df_master, df_new_orders_only], ignore_index=True)
df_all['年月日'] = pd.to_datetime(df_all['年月日'], errors='coerce')
df_all = df_all.sort_values(by=['顧客コード', '年月日'])
df_all['初回注文日'] = df_all.groupby('顧客コード')['年月日'].transform('min')

df_all['ブランド新規'] = (
    (df_all['年月日'] == df_all['初回注文日']) |
    (df_all['客区分名称'] == 'フリー')
).replace({True: "1", False: "0"})

df_all['メゾン新規'] = df_all['客区分名称'].isin(['フリー', 'エントリー']).replace({True: "1", False: "0"})

# 今回追加された注文のみに絞る
df_updated_orders_flagged = df_all[df_all['店消実績ID'].isin(df_new_orders_only['店消実績ID'])].copy()

# ------------------------------------------
# 5. スプレッドシートに追記・保存
# ------------------------------------------
df_new_storemaster = pd.concat([df_master, df_updated_orders_flagged], ignore_index=True).sort_values(by='年月日')

# ✅ 注文ごとに複数商品を含めるため「注文キー＝店消実績ID + 商品符号」で重複を定義する
combined_store_customer = pd.concat([df_master, df_updated_orders_flagged], ignore_index=True)

# 注文キーを作成（注文ID＋商品符号＋商品コード）
combined_store_customer['注文キー'] = (
    combined_store_customer['店消実績ID'].astype(str) + '_' +
    combined_store_customer['商品符号'].astype(str) + '_' +
    combined_store_customer['商品コード'].astype(str)
)

# 注文キーで重複排除（商品ごとに1行は残す）
combined_store_customer = combined_store_customer.sort_values('年月日', ascending=False)
combined_store_customer = combined_store_customer.drop_duplicates(subset='注文キー', keep='first')

# 注文キー列を削除
combined_store_customer = combined_store_customer.drop(columns='注文キー', errors='ignore')
combined_store_customer = combined_store_customer.drop(columns=['初回注文日'], errors='ignore')

#年月日降順で並び替え
combined_store_customer = combined_store_customer.sort_values('年月日', ascending=False)

# 保存
worksheet_storecustomer.clear()
set_with_dataframe(worksheet_storecustomer, combined_store_customer)

print(f"\n✅ tarte顧客データベース（店舗）追記完了！件数: {len(combined_store_customer):,}")

"""# **ステップ6:** **店舗とECの商品実績を合算集計**"""

# ============================================
# ✅ 店舗データとECデータを準備
# ============================================

# コピー
店舗_df = aggregated_store.copy()
EC_df = aggregated.copy()

# 店舗の金額列をECに合わせる
店舗_df = 店舗_df.rename(columns={'割引後合計金額': '税抜割引後金額'})

# カンマ除去・年月をdatetime・数値化
for df in [店舗_df, EC_df]:
    df['年月'] = pd.to_datetime(df['年月'], format='%Y-%m', errors='coerce')
    df['税抜割引後金額'] = df['税抜割引後金額'].astype(str).str.replace(',', '', regex=False)
    df['税抜割引後金額'] = pd.to_numeric(df['税抜割引後金額'], errors='coerce')
    df['数量'] = pd.to_numeric(df['数量'], errors='coerce')

# ============================================
# ✅ 両データを結合
# ============================================
combined_df = pd.concat([店舗_df, EC_df], ignore_index=True)

# ============================================
# ✅ 商品コード単位で集計
# ============================================
aggregated_df = combined_df.groupby(
    ['年月', '商品コード'],
    as_index=False
).agg({
    '数量': 'sum',
    '税抜割引後金額': 'sum'
})

# 念のため年月をdatetime
aggregated_df['年月'] = pd.to_datetime(aggregated_df['年月'], format='%Y-%m')

# ============================================
# ✅ 商品マスタを商品コードでJOIN
# ============================================
# category_master を事前に読み込んでいる想定
product_info_cols = ['商品コード', '商品符号', '商品名', 'メインカテゴリー', 'サブカテゴリー', 'サブサブカテゴリー']
product_master_by_code = category_master[product_info_cols].drop_duplicates(subset='商品コード', keep='first')

aggregated_df = pd.merge(
    aggregated_df,
    product_master_by_code,
    on='商品コード',
    how='left'
)

# ============================================
# ✅ スプレッドシート取得
# ============================================
spreadsheet_name = "tarte 実績データベース"
spreadsheet = gc.open(spreadsheet_name)
worksheet_totalproduct = spreadsheet.worksheet("商品実績（合算）")

# ============================================
# ✅ 既存データ読み込み
# ============================================
existing_df = get_as_dataframe(worksheet_totalproduct, evaluate_formulas=True).dropna(how='all')

if existing_df.empty:
    existing_df = pd.DataFrame(columns=aggregated_df.columns)

# 年月をdatetime
existing_df['年月'] = pd.to_datetime(existing_df['年月'], errors='coerce')

# ============================================
# ✅ 既存データと新データをキーでマージ（上書き）
# ============================================
keys = ['年月', '商品コード']

merged_df = pd.merge(
    existing_df,
    aggregated_df,
    on=keys,
    how='outer',
    suffixes=('_old', '')
)

# 数量・金額を新しいデータで上書き
merged_df['数量'] = merged_df['数量'].combine_first(merged_df['数量_old'])
merged_df['税抜割引後金額'] = merged_df['税抜割引後金額'].combine_first(merged_df['税抜割引後金額_old'])

# 商品符号・商品名・カテゴリーも新データで上書き
for col in ['商品符号', '商品名', 'メインカテゴリー', 'サブカテゴリー', 'サブサブカテゴリー']:
    merged_df[col] = merged_df[col].combine_first(merged_df[f'{col}_old'])

# 不要な旧カラムを削除
merged_df = merged_df.drop(columns=[c for c in merged_df.columns if c.endswith('_old')])

# 並べ替え
merged_df = merged_df.sort_values(['年月', '商品コード'], ascending=[False, True])

# ============================================
# ✅ 表示用整形
# ============================================
display_df = merged_df.copy()
display_df['税抜割引後金額'] = display_df['税抜割引後金額'].round(0).astype(int).map('{:,}'.format)

# 表示
display(display_df[[
    '年月', '商品符号', '商品コード', '商品名',
    'メインカテゴリー', 'サブカテゴリー', 'サブサブカテゴリー',
    '数量', '税抜割引後金額'
]].head())

# ============================================
# ✅ スプレッドシートに保存
# ============================================
worksheet_totalproduct.clear()

# スプレッドシート用に列を並べ替え
merged_df = merged_df[[
    '年月',
    '商品コード',
    '商品符号',
    '商品名',
    'メインカテゴリー',
    'サブカテゴリー',
    'サブサブカテゴリー',
    '数量',
    '税抜割引後金額'
]]

set_with_dataframe(worksheet_totalproduct, merged_df)

print("\n✅ 集計と保存が完了しました！")